# chart/values.yaml
replicaCount: 1

image:
  repository: torrefacto/flusso-ingress-controller
  tag: latest
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: flusso-ingress

service:
  type: NodePort
  port: 80
  targetPort: 8080

ingressClass: flusso

env:
  TLS_ENABLED: "true"
  SERVER_ADDR: "0.0.0.0:8080"