# templates/frontend/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
    component: frontend
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "api-gateway.labels" . | nindent 6 }}
      component: frontend
  template:
    metadata:
      labels:
        {{- include "api-gateway.labels" . | nindent 8 }}
        component: frontend
    spec:
      containers:
        - name: {{ .Values.frontend.name }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          env:
            - name: VITE_API_URL
              value: {{ .Values.frontend.env.VITE_API_URL | quote }}