# chart/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "flusso-ingress-controller.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "{{ .Values.ingressClass }}"
spec:
  rules:
    - host: "example.local"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "flusso-ingress-controller.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
