# chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flusso-ingress-controller.fullname" . }}
  labels:
    app: {{ include "flusso-ingress-controller.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: {{ include "flusso-ingress-controller.name" . }}
