apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: flussoapigateways.networking.k8s.io
  annotations:
    api-approved.kubernetes.io: "unapproved: Reason for unapproved CRD"
spec:
  group: networking.k8s.io
  names:
    kind: FlussoApiGateway
    plural: flussoapigateways
    singular: flussoapigateway
    shortNames:
      - fag
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                gatewayClassName:
                  type: string
                listeners:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      protocol:
                        type: string
                      port:
                        type: integer
            status:
              type: object
