apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-server-secrets
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.server.auth.jwtSecret | b64enc | quote }}

