apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-gateway.name" . }}-server
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: api
      port: 3000
      targetPort: 3000
      protocol: TCP
  selector:
    {{- include "api-gateway.labels" . | nindent 4 }}
    component: server

