apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flusso-ingress-controller.fullname" . }}
  labels:
    app: {{ include "flusso-ingress-controller.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "flusso-ingress-controller.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "flusso-ingress-controller.name" . }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: flusso-ingress
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
            - containerPort: 8081
            {{- if .Values.apiGateway.enabled }}
            - containerPort: {{ .Values.apiGateway.port }}
            {{- end }}
          env:
            - name: TLS_ENABLED
              value: "{{ .Values.env.TLS_ENABLED }}"
            - name: SERVER_ADDR
              value: "{{ .Values.env.SERVER_ADDR }}"
            {{- if .Values.apiGateway.enabled }}
            - name: API_GATEWAY_TLS_ENABLED
              value: "{{ .Values.apiGateway.tlsEnabled }}"
            - name: API_GATEWAY_PORT
              value: "{{ .Values.apiGateway.port }}"
            {{- end }}
