apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: gatewayroutes.gateway.custom.io
spec:
  group: gateway.custom.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                path:
                  type: string
                targetService:
                  type: string
                method:
                  type: string
                authRequired:
                  type: boolean
  scope: Namespaced
  names:
    plural: gatewayroutes
    singular: gatewayroute
    kind: GatewayRoute
    shortNames:
      - gr
