# config/crd/security-config.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: securityconfigs.gateway.flusso.io
spec:
  group: gateway.flusso.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                rateLimit:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                    requestsPerMinute:
                      type: integer
                    burstSize:
                      type: integer
                authentication:
                  type: object
                  properties:
                    jwtSecret:
                      type: string
                    tokenExpiration:
                      type: integer
                    refreshTokenEnabled:
                      type: boolean
                cors:
                  type: object
                  properties:
                    enabled:
                      type: boolean
                    allowedOrigins:
                      type: string
                    allowedMethods:
                      type: array
                      items:
                        type: string
  scope: Namespaced
  names:
    plural: securityconfigs
    singular: securityconfig
    kind: SecurityConfig
    shortNames:
      - secconf