apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-gateway.fullname" . }}
  labels:
    app: {{ include "api-gateway.name" . }}
spec:
  type: LoadBalancer
  ports:
    - name: main
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: dashboard
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: api-gateway
      port: 8082
      targetPort: {{ .Values.apiGateway.port }}
      protocol: TCP
  selector:
    app: {{ include "api-gateway.name" . }}
