apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-gateway.fullname" . }}
  labels:
    app: {{ include "api-gateway.name" . }}
spec:
  type: ClusterIP
  ports:
    - name: main
      port: 80
      targetPort: 8080
      protocol: TCP
    - name: api-rest
      port: 8081
      targetPort: 8081
      protocol: TCP
  selector:
    app: {{ include "api-gateway.name" . }}
