# templates/backend/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-backend-config
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
data:
  default.yaml: |
    server:
      host: "0.0.0.0"
      port: 3000
      timeout: 30
      workers: 4

    jwt:
      secret: "{{ .Values.backend.auth.jwtSecret }}"
      expiration: 3600
      refresh_expiration: 86400

    cors:
      allowed_origins:
        - "http://localhost:5173"
        - "https://api-gateway.example.com"
      allowed_methods:
        - "GET"
        - "POST"
        - "PUT"
        - "DELETE"
      allowed_headers:
        - "Content-Type"
        - "Authorization"
      max_age: 3600

    metrics:
      enabled: true
      path: "/metrics"

    rate_limit:
      enabled: true
      requests_per_second: 100
      burst_size: 50

    logging:
      level: "info"
      format: "json"

    database:
      url: "postgres://postgres:postgres@localhost/api_gateway"
      max_connections: 5