# templates/backend/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-backend-secrets
  labels:
    {{- include "api-gateway.labels" . | nindent 4 }}
type: Opaque
data:
  jwt-secret: {{ .Values.backend.auth.jwtSecret | b64enc | quote }}