# values.yaml
replicaCount: 1

image:
  repository: diocrafts/flusso-api-gateway
  tag: v0.0.92
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi

env:
  # Variables de entorno para tu backend y/o frontend
  JWT_SECRET: "your-secret-key-change-in-production"
  RUST_LOG: "info"
  RUST_BACKTRACE: "1"
  # Otras que necesites: API_URL, etc.

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: flusso.example.com
      paths:
        - path: /
          pathType: Prefix